Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Max: 50
Style/SymbolProc:
  # Style/SymbolProc can break when using map with refine in Ruby 2.4>
  Enabled: false
Style/FrozenStringLiteralComment:
  # This rule doesn't work when run locally
  Enabled: false
Style/SafeNavigation:
  # This rule doesn't work when run locally
  Enabled: false
Style/NumericPredicate:
  # This rule doesn't work when run locally
  Enabled: false
AllCops:
  Exclude:
    - '**/node_modules/**/*'
    - '**/vendor/**/*'
    - '**/bundle/**/*'
Metrics/LineLength:
  Exclude:
    - 'Contents/Resources/test/tc_javascript.rb'
    - 'Contents/Resources/test/tc_parser.rb'
    - 'Contents/Resources/test/tc_search.rb'
    - 'Contents/Resources/test/scripts/test_data_json.rb'
    - 'Contents/Resources/test/scripts/test_search_output.rb'
    - 'Contents/Resources/test/tc_controller.rb'
    - 'Contents/Resources/search.rb'
